language: cpp
before_install:
  - $CXX --version
  - wget http://www.cmake.org/files/v3.4/cmake-3.4.3.tar.gz 
  - tar -xvzf cmake-3.4.3.tar.gz 
  - cd cmake-3.4.3
  - ./configure
  - make
  - sudo make install
  - sudo update-alternatives --install /usr/bin/cmake cmake /usr/local/bin/cmake 1 --force 
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev
  - sudo apt-get install libgomp1
  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  - sudo apt-get install git-lfs
  - git lfs install
  - ./install-ad-libraries
script:
  - cd comparison-with-ad-libraries
  - cd ex1
  - mkdir build && cd build
  - cmake .. && make
  - cd ../..
  - cd ex2
  - mkdir build && cd build
  - cmake .. && make
  - cd ../..
  - cd ex3
  - mkdir build && cd build
  - cmake .. && make
  - cd ../..
  
after_success:
  - ex1/build/compare
  - ex2/build/compare
  - ex3/build/compare



